db:
  uri: "postgresql+asyncpg://demo:demo@localhost/demo"
cve_repo:
  repo_url: "https://github.com/CVEProject/cvelistV5"
  commits_url: "${cve_repo.url}/commits"
  data_dir: cve_data
  interval_update: 6
