db:
  uri: "postgresql+asyncpg://demo:demo@localhost/demo"
  echo: ${oc.env:DB_ECHO,"false"}
cve_repo:
  repo_url: "https://github.com/CVEProject/cvelistV5"
  data_dir: "cve_data"
  cves_folder: "${cve_repo.data_dir}/cves"
  delta_log_path: "${cve_repo.data_dir}/cves/deltaLog.json"
  update_interval_hours: 6
  batch_size: 1000
